server:
  port: 8763

spring:
  application:
    name: client1
  zipkin:
    base-url: http://127.0.0.1:8899  #zipkin服务端地址
  sleuth:
    sampler:
      probability: 1.0  #调用链信息采样率
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'