#本机端口
server:
  port: 8899

#服务名
spring:
  application:
    name: zipkin-server

#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#关闭自动收集web请求
management:
  metrics:
    web:
      server:
        auto-time-requests: false