eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://127.0.0.1:8899  #zipkin服务端地址
  sleuth:
    sampler:
      probability: 1.0  #调用链信息采样率